// <auto-generated />
using System;
using IntelliINPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntelliINPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614114750_AddTrademarkOwnerLinks")]
    partial class AddTrademarkOwnerLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntelliINPI.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.ImportJobLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId");

                    b.ToTable("ImportJobLogs");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.MonitoredTrademark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasPendingChanges")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastKnownDispatchCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("LastKnownDispatchDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("LastKnownDispatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProcessNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TrademarkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastKnownDispatchId");

                    b.HasIndex("ProcessNumber");

                    b.HasIndex("TrademarkId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TrademarkId")
                        .IsUnique();

                    b.ToTable("MonitoredTrademarks");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.RpiHistoricalImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentRpi")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateDispatches")
                        .HasColumnType("integer");

                    b.Property<int>("EndRpi")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FailedRpis")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SkippedRpis")
                        .HasColumnType("integer");

                    b.Property<int>("StartRpi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SuccessfulRpis")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDispatchesImported")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRpis")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("RpiHistoricalImportRuns");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.RpiImportCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DispatchesImported")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateDispatches")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FailedRows")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RpiNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("XmlOrTxtFilesCount")
                        .HasColumnType("integer");

                    b.Property<string>("ZipPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("RpiNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("RpiImportCheckpoints");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.Trademark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FilingDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProcessNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Trademarks");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("PublishedAt")
                        .HasColumnType("date");

                    b.Property<int?>("RpiNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrademarkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrademarkId", "RpiNumber", "Code")
                        .IsUnique();

                    b.ToTable("TrademarkDispatches");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkMonitoringEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentDispatchCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("CurrentDispatchDate")
                        .HasColumnType("date");

                    b.Property<Guid>("DispatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MonitoredTrademarkId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousDispatchCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("PreviousDispatchDate")
                        .HasColumnType("date");

                    b.Property<string>("ProcessNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TrademarkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId");

                    b.HasIndex("IsRead");

                    b.HasIndex("MonitoredTrademarkId");

                    b.HasIndex("TrademarkId");

                    b.ToTable("TrademarkMonitoringEvents");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkNiceClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClassNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Specification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TrademarkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("TrademarkId", "Code")
                        .IsUnique();

                    b.ToTable("TrademarkNiceClasses");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Document")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("TrademarkOwners");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkOwnerLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrademarkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TrademarkId", "OwnerId")
                        .IsUnique();

                    b.ToTable("TrademarkOwnerLinks");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TrademarkStatuses");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.ImportJobLog", b =>
                {
                    b.HasOne("IntelliINPI.Domain.Entities.ImportJob", "ImportJob")
                        .WithMany("Logs")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.MonitoredTrademark", b =>
                {
                    b.HasOne("IntelliINPI.Domain.Entities.TrademarkDispatch", "LastKnownDispatch")
                        .WithMany()
                        .HasForeignKey("LastKnownDispatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntelliINPI.Domain.Entities.Trademark", "Trademark")
                        .WithMany("Monitors")
                        .HasForeignKey("TrademarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliINPI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastKnownDispatch");

                    b.Navigation("Trademark");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.Trademark", b =>
                {
                    b.HasOne("IntelliINPI.Domain.Entities.TrademarkOwner", "Owner")
                        .WithMany("Trademarks")
                        .HasForeignKey("OwnerId");

                    b.HasOne("IntelliINPI.Domain.Entities.TrademarkStatus", "Status")
                        .WithMany("Trademarks")
                        .HasForeignKey("StatusId");

                    b.Navigation("Owner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkDispatch", b =>
                {
                    b.HasOne("IntelliINPI.Domain.Entities.Trademark", "Trademark")
                        .WithMany("Dispatches")
                        .HasForeignKey("TrademarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trademark");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkMonitoringEvent", b =>
                {
                    b.HasOne("IntelliINPI.Domain.Entities.TrademarkDispatch", "Dispatch")
                        .WithMany()
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliINPI.Domain.Entities.MonitoredTrademark", "MonitoredTrademark")
                        .WithMany("Events")
                        .HasForeignKey("MonitoredTrademarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliINPI.Domain.Entities.Trademark", "Trademark")
                        .WithMany()
                        .HasForeignKey("TrademarkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dispatch");

                    b.Navigation("MonitoredTrademark");

                    b.Navigation("Trademark");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkNiceClass", b =>
                {
                    b.HasOne("IntelliINPI.Domain.Entities.Trademark", "Trademark")
                        .WithMany("NiceClasses")
                        .HasForeignKey("TrademarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trademark");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkOwnerLink", b =>
                {
                    b.HasOne("IntelliINPI.Domain.Entities.TrademarkOwner", "Owner")
                        .WithMany("TrademarkLinks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliINPI.Domain.Entities.Trademark", "Trademark")
                        .WithMany("OwnerLinks")
                        .HasForeignKey("TrademarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Trademark");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.ImportJob", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.MonitoredTrademark", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.Trademark", b =>
                {
                    b.Navigation("Dispatches");

                    b.Navigation("Monitors");

                    b.Navigation("NiceClasses");

                    b.Navigation("OwnerLinks");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkOwner", b =>
                {
                    b.Navigation("TrademarkLinks");

                    b.Navigation("Trademarks");
                });

            modelBuilder.Entity("IntelliINPI.Domain.Entities.TrademarkStatus", b =>
                {
                    b.Navigation("Trademarks");
                });
#pragma warning restore 612, 618
        }
    }
}
