"use client";
import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Search, Trash2, Users } from "lucide-react";
import { deleteNitResearcher, listNitInstitutions, listNitResearchers, saveNitResearcher } from "@/lib/queries";
import type { NitResearcherPayload } from "@/lib/types";

const blank: NitResearcherPayload = { institutionId: "", name: "", cpf: null, email: null, phone: null, department: null, position: null, lattesUrl: null, orcid: null, specialties: null, technologyAreas: null };
export default function ResearchersPage() { const qc = useQueryClient(); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [form, setForm] = useState(blank); const institutions = useQuery({ queryKey: ["nit-institutions"], queryFn: listNitInstitutions }); const query = useQuery({ queryKey: ["nit-researchers", search, page], queryFn: () => listNitResearchers({ search, page, pageSize: 20 }) }); const save = useMutation({ mutationFn: () => saveNitResearcher(form), onSuccess: () => { setForm(blank); qc.invalidateQueries({ queryKey: ["nit-researchers"] }); } }); const remove = useMutation({ mutationFn: deleteNitResearcher, onSuccess: () => qc.invalidateQueries({ queryKey: ["nit-researchers"] }) });
return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Pesquisadores</h1><p className="text-sm text-slate-500">Inventores e pesquisadores vinculados às instituições.</p></div><form onSubmit={(e) => { e.preventDefault(); save.mutate(); }} className="grid gap-3 rounded-lg border border-line bg-white p-4 shadow-panel md:grid-cols-4"><label className="text-sm">Instituição<select className="input mt-1" required value={form.institutionId} onChange={e => setForm({ ...form, institutionId: e.target.value })}><option value="">Selecione</option>{institutions.data?.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{([['Nome','name'],['CPF','cpf'],['E-mail','email'],['Telefone','phone'],['Departamento','department'],['Cargo','position'],['Currículo Lattes','lattesUrl'],['ORCID','orcid'],['Especialidades','specialties'],['Áreas tecnológicas','technologyAreas']] as const).map(([label,key]) => <label className="text-sm" key={key}>{label}<input className="input mt-1" required={key === 'name'} value={form[key] ?? ""} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<button className="btn-primary self-end">Cadastrar</button></form>
<div className="flex max-w-md items-center gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input className="input pl-9" placeholder="Buscar por nome, CPF ou e-mail" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></div></div>
<div className="overflow-hidden rounded-lg border border-line bg-white shadow-panel"><table className="w-full text-sm"><thead><tr className="bg-slate-50 text-left"><th className="p-3">Pesquisador</th><th>Instituição</th><th>Departamento</th><th>Áreas</th><th>Invenções</th><th /></tr></thead><tbody>{query.data?.items.map(x => <tr key={x.id} className="border-t border-line"><td className="p-3 font-medium">{x.name}<span className="block text-xs font-normal text-slate-500">{x.email || x.cpf || "Sem contato"}</span></td><td>{x.institutionName}</td><td>{x.department || "-"}</td><td>{x.technologyAreas || "-"}</td><td>{x.inventionsCount}</td><td><button title="Desativar" className="icon-button text-red-600" onClick={() => remove.mutate(x.id)}><Trash2 size={16} /></button></td></tr>)}</tbody></table><div className="flex items-center justify-between border-t p-3 text-sm"><span>{query.data?.totalItems ?? 0} pesquisadores</span><div className="flex gap-2"><button className="btn-secondary" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Anterior</button><button className="btn-secondary" disabled={(query.data?.items.length ?? 0) < 20} onClick={() => setPage(p => p + 1)}>Próxima</button></div></div></div></div>; }
